### ISSUE TITLE
Simplify config

### ISSUE THREAD

**Issue by pvsr** [pvsr/qute-ssb#3]
What if instead of the complicated config, there was just a shell script like:
```
ln -s {{ xdg-config-qb }}/qutebrowser.conf {{ dest-config-qb }}/qutebrowser.conf
mkdir -p {{ dest-config-qb }}/conf.d
cp {{ xdg-config-qb }}/conf.d/* {{ dest-config-qb }}/conf.d/
```

**Comment by pvsr** [comment]
Maybe each top-level section can have a fixed location and all its children could be interpreted as files. That would replace
```toml
[basedir]
location = "{{ basedir }}"
[basedir.dirs.config.files."config.py"]
link = "/some/file"
[basedir.dirs.config.dirs."conf.d".files.x]
template = "x.py"
```
with
```toml
[basedir]
[basedir."config.py"]
path_from_parent = "config/"
link = "/some/file"
[basedir.x]
path_from_parent = "config/conf.d/"
template = "x.py"
```

Is that an improvement? Maybe not, actually.

**Comment by pvsr** [comment]
There's also
```toml
[basedir]
[basedir."config/config.py"]
link = "/some/file"
[basedir."config/conf.d/x"]
template = "x.py"
```
